// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Task_entity.Models;

#nullable disable

namespace Task_entity.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF_Task_1.Data.Taask", b =>
                {
                    b.Property<int>("TaaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaaskId"));

                    b.Property<DateTime>("TaaskDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Deadline");

                    b.Property<string>("TaaskDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaaskTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TaaskId");

                    b.ToTable("NewTask", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
